config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators, only: [:create, :build, :destroy]
  end
  resources :charges, only: [:new, :create, :destroy]
  devise_for :users, controllers: {registrations: 'registrations'}
  get 'about' => 'welcome#about'
  root 'welcome#index'
  resources :users do
    member do
      get :confirm_email
    end
  end

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
  def self.wikis
    Wiki.where(id: pluck(:wiki_id))
  end
  def self.users
    User.where(id: pluck(:user_id))
  end
  def user
    User.find(user_id)
  end
  def wiki
    Wiki.find(wiki_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :wikis, through: :collaborators
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:admin, :standard, :premium]
  after_initialize :set_default_role, :if => :new_record?
  delegate :wikis, to: :collaborators

  def set_default_role
    self.role ||= :standard
  end
  def collaborators
    Collaborator.where(user_id: id)
  end

  # def admin?
  #   role == 0
  # end
  # def standard?
  #   role == 1
  # end
  # def premium?
  #   role == 2
  # end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  delegate :users, to: :collaborators
  def collaborators
    Collaborator.where(wiki_id: id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  after_action :verify_authorized, :except => :index, unless: :devise_controller?
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  skip_after_action :verify_authorized
  Stripe.api_key = ENV['SECRET_KEY']
  def new
  end

  def create
    # Amount in cents
    @amount = 1500
    customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
    )

    stripe_charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
    )
    current_user.role = 2
    current_user.stripe_id = customer.id
    current_user.save

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end


  def destroy

    puts "insdie the destroy"
    puts current_user.stripe_id
    customer = Stripe::Customer.retrieve(
    current_user.stripe_id.to_s,
    :api_key => Stripe.api_key
    )

    if customer.delete
      flash[:notice] = "Charge was deleted."
      current_user.role = 1
      current_user.stripe_id = nil
      current_user.wikis.each do |w|
        puts w.private
        w.private = false
      end
      current_user.save
      redirect_to wikis_path
    else
      flash[:alert] = "Comment couldn't be deleted. Try again."
      redirect_to charge_path
    end
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  skip_after_action :verify_authorized
  def create
      @wiki = Wiki.find(params[:wiki_id])
      id = "#{params[:collaborator]}"
    
      @user = User.where(id: id).first


      @collaborator = Collaborator.new
      #Wiki.users.new
      # collaborator = current_user.collaborator.build(wiki: wiki, user: user)
      @collaborator.wiki_id = @wiki.id
      @collaborator.user_id = @user.id
      @collaborator.email = @user.email

      if @collaborator.save
        flash[:notice] = "Added a collaborator"
      else
        flash[:alert] = "can't add a collaborator"
      end
      redirect_to @wiki
  end
  def build
    #this builds a collaborator list on a wiki.
    @wiki = Wiki.find(params[:wiki_id])

  end
  def destroy

    @wiki = Wiki.find(params[:wiki_id])
    id = "#{params[:id]}"
    @user = User.where(id: id).first
    @collaborator = @wiki.collaborators.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "Removed a collaborator"
    else
      flash[:alert] = "can't add a collaborator"
    end
    redirect_to @wiki

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def after_sign_up_path_for(resource)
    '/wikis'
    # '/charges/new'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_after_action :verify_authorized
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    # @wikis = Wiki.all
    @wikis = policy_scope(Wiki)
    # authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
 # #9

     @wiki = Wiki.new
     authorize @wiki
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]
     @wiki.private = params[:wiki][:private]
     @wiki.user_id = current_user.id

 # #10
     if @wiki.save
 # #11
       flash[:notice] = "Wiki has been saved."
       redirect_to @wiki
     else
 # #12
       flash.now[:alert] = "There was an error saving the Wiki. Please try again."
       render :new
     end

  end


  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    if @wiki.save
      flash[:notice] = "Post was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :edit
    end
  end
  def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki
     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      underline:          true,
      strikethrough:      true
      # disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$15.00</strong>! for your premium subscription</h2>
<div class="row">
  <div class="col-md-8">
    <p><%= link_to "Back to Wikis", wikis_path %> </p>
    <!-- <%= link_to "Downgrade your premium a/c", charge_path(current_user), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade your a/c?'}  %> -->
  </div>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-8">
        <p class="charges-info">Pay with card to upgrade your monthly subscription to a premium user of Infopedia</p>
        <p class="charges-info">As a premium user you can create private Wikis and only you can edit these wikis. </p>
      </div>
    </div>
    <label class="amount">
      <span>Amount: $15.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="1500"
          data-locale="auto"></script>
<% end %>

app/views/collaborators/_collaborator.html.erb
<%= form_tag [wiki, Collaborator], method: :wiki do %>
  <% user_list = User.where.not(id: current_user)
                      .where.not(id: wiki.users)
                      .all %>

    <div class="form-group">
      <%= select_tag :collaborator, options_from_collection_for_select(user_list, "id", "email", params[:id].to_i), rows: 8, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag "Add a collaborator", class: "btn btn-basic" %>
      <% if Collaborator.count > 0 %>
        <% col_list = Collaborator.where.not(id: current_user)
                            .all%>
    </div>
  <% end %>
  <%= div_for(col_list) do |collab| %>
    <%= collab.email %>
    <%= link_to "Remove", wiki_collaborator_path(:wiki_id=>wiki.id, :id=>collab.id), method: :delete, data: {confirm: 'Are you sure you want to remove this user?'} %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infopedia</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="page-color">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Infopedia</a>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <li><%= link_to current_user.email, edit_user_registration_path %></li>
         <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
        <% else %>
         <li><%= link_to "Sign Up", new_user_registration_path %></li>
         <li><%= link_to "Sign In", new_user_session_path %></li>
       <% end %>
       <% if user_signed_in? %>
         <% if current_user.standard? %>
            <li><%= link_to "Upgrade to premium account", new_charge_path(current_user) %> </li>
          <% else %>
            <li><%= link_to "Cancel premium account", charge_path(current_user), method: :delete,  data: {confirm: 'Are you sure you want to unsubscribe?'}  %> </li>
            <% end %>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="notice"><%= notice %></div>
  <div class="alert"><%= alert %></div>
<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 page-header">
    About Infopedia
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>Find me in app/views/welcome/about.html.erb</p>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Welcome to Infopedia!</h1>
      <h3>Create wikis and share the knowledge</h3>
    </div>
  </div
</div>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 page-header">
    Edit Wiki
  </div>
</div>
<div class="row">
 <div class="col-md-8 col-md-offset-2">
   <%= form_for @wiki do |f| %>
     <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
     </div>
     <div class="form-group">
       <%= f.label :body %>
       <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki contents" %>
     </div>

     <div class="form-group">
       <%= f.label :private %>
       <%= f.check_box :private, placeholder: "Private" %>
     </div>

     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-basic btn-block' %>
     </div>

   <% end %>

   <% if current_user %>
    <%= render partial: 'collaborators/collaborator', locals: { wiki: @wiki }%>
   <% end %>

 </div>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 page-header">
    List of all the Wikis
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% @wikis.each do |wiki| %>
      <div class="list-group">
        <h4><%= link_to wiki.title, wiki, class: "list-group-item" %></h4>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if policy(Wiki).new? %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-new-wiki btn-block' %>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 page-header">
    Create New Wiki
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki contents" %>
       </div>
       <% if current_user.premium? || current_user.admin?%>
         <div class="form-group">
           <%= f.label :private%>
           <%= f.check_box :private %>
         </div>
      <% end %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success btn-block' %>
       </div>
     <% end %>

  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %>
      <%= check_box_tag "private", @wiki.private, @wiki.private, disabled: true %>
    </p>
  </div>
  <div class="col-md-4">
    <% if policy(@wiki).update? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
   </div>
 </div>
  </div>
</div>